package cn.edu.xupt.help.notice.mapper;

import cn.edu.xupt.help.framework.domain.TbNotice;
import cn.edu.xupt.help.framework.domain.TbNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TbNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated
     */
    int countByExample(TbNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated
     */
    int deleteByExample(TbNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated
     */
    int insert(TbNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated
     */
    int insertSelective(TbNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated
     */
    List<TbNotice> selectByExample(TbNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated
     */
    TbNotice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbNotice record, @Param("example") TbNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbNotice record, @Param("example") TbNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbNotice record);
}