package cn.edu.xupt.help.message.mapper;

import cn.edu.xupt.help.framework.domain.TbMessageImages;
import cn.edu.xupt.help.framework.domain.TbMessageImagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TbMessageImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_images
     *
     * @mbggenerated
     */
    int countByExample(TbMessageImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_images
     *
     * @mbggenerated
     */
    int deleteByExample(TbMessageImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_images
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_images
     *
     * @mbggenerated
     */
    int insert(TbMessageImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_images
     *
     * @mbggenerated
     */
    int insertSelective(TbMessageImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_images
     *
     * @mbggenerated
     */
    List<TbMessageImages> selectByExample(TbMessageImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_images
     *
     * @mbggenerated
     */
    TbMessageImages selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_images
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbMessageImages record, @Param("example") TbMessageImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_images
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbMessageImages record, @Param("example") TbMessageImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbMessageImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbMessageImages record);
}