package cn.edu.xupt.help.message.mapper;

import cn.edu.xupt.help.framework.domain.TbMessageCollect;
import cn.edu.xupt.help.framework.domain.TbMessageCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TbMessageCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_collect
     *
     * @mbggenerated
     */
    int countByExample(TbMessageCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_collect
     *
     * @mbggenerated
     */
    int deleteByExample(TbMessageCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_collect
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_collect
     *
     * @mbggenerated
     */
    int insert(TbMessageCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_collect
     *
     * @mbggenerated
     */
    int insertSelective(TbMessageCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_collect
     *
     * @mbggenerated
     */
    List<TbMessageCollect> selectByExample(TbMessageCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_collect
     *
     * @mbggenerated
     */
    TbMessageCollect selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_collect
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbMessageCollect record, @Param("example") TbMessageCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_collect
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbMessageCollect record, @Param("example") TbMessageCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_collect
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbMessageCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_collect
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbMessageCollect record);
}