package cn.edu.xupt.help.message.mapper;

import cn.edu.xupt.help.framework.domain.TbMessageCategory;
import cn.edu.xupt.help.framework.domain.TbMessageCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TbMessageCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_category
     *
     * @mbggenerated
     */
    int countByExample(TbMessageCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_category
     *
     * @mbggenerated
     */
    int deleteByExample(TbMessageCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_category
     *
     * @mbggenerated
     */
    int insert(TbMessageCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_category
     *
     * @mbggenerated
     */
    int insertSelective(TbMessageCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_category
     *
     * @mbggenerated
     */
    List<TbMessageCategory> selectByExample(TbMessageCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_category
     *
     * @mbggenerated
     */
    TbMessageCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbMessageCategory record, @Param("example") TbMessageCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbMessageCategory record, @Param("example") TbMessageCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbMessageCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbMessageCategory record);
}