package cn.edu.xupt.help.message.mapper;

import cn.edu.xupt.help.framework.domain.TbMessage;
import cn.edu.xupt.help.framework.domain.TbMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TbMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbggenerated
     */
    int countByExample(TbMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbggenerated
     */
    int deleteByExample(TbMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbggenerated
     */
    int insert(TbMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbggenerated
     */
    int insertSelective(TbMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbggenerated
     */
    List<TbMessage> selectByExample(TbMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbggenerated
     */
    TbMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbMessage record, @Param("example") TbMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbMessage record, @Param("example") TbMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbMessage record);
}