package cn.edu.xupt.help.framework.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbCommentReplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    public TbCommentReplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andReplyTypeIsNull() {
            addCriterion("reply_type is null");
            return (Criteria) this;
        }

        public Criteria andReplyTypeIsNotNull() {
            addCriterion("reply_type is not null");
            return (Criteria) this;
        }

        public Criteria andReplyTypeEqualTo(String value) {
            addCriterion("reply_type =", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeNotEqualTo(String value) {
            addCriterion("reply_type <>", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeGreaterThan(String value) {
            addCriterion("reply_type >", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("reply_type >=", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeLessThan(String value) {
            addCriterion("reply_type <", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeLessThanOrEqualTo(String value) {
            addCriterion("reply_type <=", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeLike(String value) {
            addCriterion("reply_type like", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeNotLike(String value) {
            addCriterion("reply_type not like", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeIn(List<String> values) {
            addCriterion("reply_type in", values, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeNotIn(List<String> values) {
            addCriterion("reply_type not in", values, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeBetween(String value1, String value2) {
            addCriterion("reply_type between", value1, value2, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeNotBetween(String value1, String value2) {
            addCriterion("reply_type not between", value1, value2, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyIdIsNull() {
            addCriterion("reply_id is null");
            return (Criteria) this;
        }

        public Criteria andReplyIdIsNotNull() {
            addCriterion("reply_id is not null");
            return (Criteria) this;
        }

        public Criteria andReplyIdEqualTo(Long value) {
            addCriterion("reply_id =", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdNotEqualTo(Long value) {
            addCriterion("reply_id <>", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdGreaterThan(Long value) {
            addCriterion("reply_id >", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("reply_id >=", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdLessThan(Long value) {
            addCriterion("reply_id <", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdLessThanOrEqualTo(Long value) {
            addCriterion("reply_id <=", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdIn(List<Long> values) {
            addCriterion("reply_id in", values, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdNotIn(List<Long> values) {
            addCriterion("reply_id not in", values, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdBetween(Long value1, Long value2) {
            addCriterion("reply_id between", value1, value2, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdNotBetween(Long value1, Long value2) {
            addCriterion("reply_id not between", value1, value2, "replyId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNull() {
            addCriterion("comment_id is null");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNotNull() {
            addCriterion("comment_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommentIdEqualTo(Long value) {
            addCriterion("comment_id =", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotEqualTo(Long value) {
            addCriterion("comment_id <>", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThan(Long value) {
            addCriterion("comment_id >", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("comment_id >=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThan(Long value) {
            addCriterion("comment_id <", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThanOrEqualTo(Long value) {
            addCriterion("comment_id <=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIn(List<Long> values) {
            addCriterion("comment_id in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotIn(List<Long> values) {
            addCriterion("comment_id not in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdBetween(Long value1, Long value2) {
            addCriterion("comment_id between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotBetween(Long value1, Long value2) {
            addCriterion("comment_id not between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andFromUidIsNull() {
            addCriterion("from_uid is null");
            return (Criteria) this;
        }

        public Criteria andFromUidIsNotNull() {
            addCriterion("from_uid is not null");
            return (Criteria) this;
        }

        public Criteria andFromUidEqualTo(Long value) {
            addCriterion("from_uid =", value, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidNotEqualTo(Long value) {
            addCriterion("from_uid <>", value, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidGreaterThan(Long value) {
            addCriterion("from_uid >", value, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidGreaterThanOrEqualTo(Long value) {
            addCriterion("from_uid >=", value, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidLessThan(Long value) {
            addCriterion("from_uid <", value, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidLessThanOrEqualTo(Long value) {
            addCriterion("from_uid <=", value, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidIn(List<Long> values) {
            addCriterion("from_uid in", values, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidNotIn(List<Long> values) {
            addCriterion("from_uid not in", values, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidBetween(Long value1, Long value2) {
            addCriterion("from_uid between", value1, value2, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidNotBetween(Long value1, Long value2) {
            addCriterion("from_uid not between", value1, value2, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgIsNull() {
            addCriterion("from_thumb_img is null");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgIsNotNull() {
            addCriterion("from_thumb_img is not null");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgEqualTo(String value) {
            addCriterion("from_thumb_img =", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgNotEqualTo(String value) {
            addCriterion("from_thumb_img <>", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgGreaterThan(String value) {
            addCriterion("from_thumb_img >", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgGreaterThanOrEqualTo(String value) {
            addCriterion("from_thumb_img >=", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgLessThan(String value) {
            addCriterion("from_thumb_img <", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgLessThanOrEqualTo(String value) {
            addCriterion("from_thumb_img <=", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgLike(String value) {
            addCriterion("from_thumb_img like", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgNotLike(String value) {
            addCriterion("from_thumb_img not like", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgIn(List<String> values) {
            addCriterion("from_thumb_img in", values, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgNotIn(List<String> values) {
            addCriterion("from_thumb_img not in", values, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgBetween(String value1, String value2) {
            addCriterion("from_thumb_img between", value1, value2, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgNotBetween(String value1, String value2) {
            addCriterion("from_thumb_img not between", value1, value2, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromNickNameIsNull() {
            addCriterion("from_nick_name is null");
            return (Criteria) this;
        }

        public Criteria andFromNickNameIsNotNull() {
            addCriterion("from_nick_name is not null");
            return (Criteria) this;
        }

        public Criteria andFromNickNameEqualTo(String value) {
            addCriterion("from_nick_name =", value, "fromNickName");
            return (Criteria) this;
        }

        public Criteria andFromNickNameNotEqualTo(String value) {
            addCriterion("from_nick_name <>", value, "fromNickName");
            return (Criteria) this;
        }

        public Criteria andFromNickNameGreaterThan(String value) {
            addCriterion("from_nick_name >", value, "fromNickName");
            return (Criteria) this;
        }

        public Criteria andFromNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("from_nick_name >=", value, "fromNickName");
            return (Criteria) this;
        }

        public Criteria andFromNickNameLessThan(String value) {
            addCriterion("from_nick_name <", value, "fromNickName");
            return (Criteria) this;
        }

        public Criteria andFromNickNameLessThanOrEqualTo(String value) {
            addCriterion("from_nick_name <=", value, "fromNickName");
            return (Criteria) this;
        }

        public Criteria andFromNickNameLike(String value) {
            addCriterion("from_nick_name like", value, "fromNickName");
            return (Criteria) this;
        }

        public Criteria andFromNickNameNotLike(String value) {
            addCriterion("from_nick_name not like", value, "fromNickName");
            return (Criteria) this;
        }

        public Criteria andFromNickNameIn(List<String> values) {
            addCriterion("from_nick_name in", values, "fromNickName");
            return (Criteria) this;
        }

        public Criteria andFromNickNameNotIn(List<String> values) {
            addCriterion("from_nick_name not in", values, "fromNickName");
            return (Criteria) this;
        }

        public Criteria andFromNickNameBetween(String value1, String value2) {
            addCriterion("from_nick_name between", value1, value2, "fromNickName");
            return (Criteria) this;
        }

        public Criteria andFromNickNameNotBetween(String value1, String value2) {
            addCriterion("from_nick_name not between", value1, value2, "fromNickName");
            return (Criteria) this;
        }

        public Criteria andToUidIsNull() {
            addCriterion("to_uid is null");
            return (Criteria) this;
        }

        public Criteria andToUidIsNotNull() {
            addCriterion("to_uid is not null");
            return (Criteria) this;
        }

        public Criteria andToUidEqualTo(Long value) {
            addCriterion("to_uid =", value, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidNotEqualTo(Long value) {
            addCriterion("to_uid <>", value, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidGreaterThan(Long value) {
            addCriterion("to_uid >", value, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidGreaterThanOrEqualTo(Long value) {
            addCriterion("to_uid >=", value, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidLessThan(Long value) {
            addCriterion("to_uid <", value, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidLessThanOrEqualTo(Long value) {
            addCriterion("to_uid <=", value, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidIn(List<Long> values) {
            addCriterion("to_uid in", values, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidNotIn(List<Long> values) {
            addCriterion("to_uid not in", values, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidBetween(Long value1, Long value2) {
            addCriterion("to_uid between", value1, value2, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidNotBetween(Long value1, Long value2) {
            addCriterion("to_uid not between", value1, value2, "toUid");
            return (Criteria) this;
        }

        public Criteria andToThumbImgIsNull() {
            addCriterion("to_thumb_img is null");
            return (Criteria) this;
        }

        public Criteria andToThumbImgIsNotNull() {
            addCriterion("to_thumb_img is not null");
            return (Criteria) this;
        }

        public Criteria andToThumbImgEqualTo(String value) {
            addCriterion("to_thumb_img =", value, "toThumbImg");
            return (Criteria) this;
        }

        public Criteria andToThumbImgNotEqualTo(String value) {
            addCriterion("to_thumb_img <>", value, "toThumbImg");
            return (Criteria) this;
        }

        public Criteria andToThumbImgGreaterThan(String value) {
            addCriterion("to_thumb_img >", value, "toThumbImg");
            return (Criteria) this;
        }

        public Criteria andToThumbImgGreaterThanOrEqualTo(String value) {
            addCriterion("to_thumb_img >=", value, "toThumbImg");
            return (Criteria) this;
        }

        public Criteria andToThumbImgLessThan(String value) {
            addCriterion("to_thumb_img <", value, "toThumbImg");
            return (Criteria) this;
        }

        public Criteria andToThumbImgLessThanOrEqualTo(String value) {
            addCriterion("to_thumb_img <=", value, "toThumbImg");
            return (Criteria) this;
        }

        public Criteria andToThumbImgLike(String value) {
            addCriterion("to_thumb_img like", value, "toThumbImg");
            return (Criteria) this;
        }

        public Criteria andToThumbImgNotLike(String value) {
            addCriterion("to_thumb_img not like", value, "toThumbImg");
            return (Criteria) this;
        }

        public Criteria andToThumbImgIn(List<String> values) {
            addCriterion("to_thumb_img in", values, "toThumbImg");
            return (Criteria) this;
        }

        public Criteria andToThumbImgNotIn(List<String> values) {
            addCriterion("to_thumb_img not in", values, "toThumbImg");
            return (Criteria) this;
        }

        public Criteria andToThumbImgBetween(String value1, String value2) {
            addCriterion("to_thumb_img between", value1, value2, "toThumbImg");
            return (Criteria) this;
        }

        public Criteria andToThumbImgNotBetween(String value1, String value2) {
            addCriterion("to_thumb_img not between", value1, value2, "toThumbImg");
            return (Criteria) this;
        }

        public Criteria andToNickNameIsNull() {
            addCriterion("to_nick_name is null");
            return (Criteria) this;
        }

        public Criteria andToNickNameIsNotNull() {
            addCriterion("to_nick_name is not null");
            return (Criteria) this;
        }

        public Criteria andToNickNameEqualTo(String value) {
            addCriterion("to_nick_name =", value, "toNickName");
            return (Criteria) this;
        }

        public Criteria andToNickNameNotEqualTo(String value) {
            addCriterion("to_nick_name <>", value, "toNickName");
            return (Criteria) this;
        }

        public Criteria andToNickNameGreaterThan(String value) {
            addCriterion("to_nick_name >", value, "toNickName");
            return (Criteria) this;
        }

        public Criteria andToNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("to_nick_name >=", value, "toNickName");
            return (Criteria) this;
        }

        public Criteria andToNickNameLessThan(String value) {
            addCriterion("to_nick_name <", value, "toNickName");
            return (Criteria) this;
        }

        public Criteria andToNickNameLessThanOrEqualTo(String value) {
            addCriterion("to_nick_name <=", value, "toNickName");
            return (Criteria) this;
        }

        public Criteria andToNickNameLike(String value) {
            addCriterion("to_nick_name like", value, "toNickName");
            return (Criteria) this;
        }

        public Criteria andToNickNameNotLike(String value) {
            addCriterion("to_nick_name not like", value, "toNickName");
            return (Criteria) this;
        }

        public Criteria andToNickNameIn(List<String> values) {
            addCriterion("to_nick_name in", values, "toNickName");
            return (Criteria) this;
        }

        public Criteria andToNickNameNotIn(List<String> values) {
            addCriterion("to_nick_name not in", values, "toNickName");
            return (Criteria) this;
        }

        public Criteria andToNickNameBetween(String value1, String value2) {
            addCriterion("to_nick_name between", value1, value2, "toNickName");
            return (Criteria) this;
        }

        public Criteria andToNickNameNotBetween(String value1, String value2) {
            addCriterion("to_nick_name not between", value1, value2, "toNickName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_comment_reply
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}