package cn.edu.xupt.help.framework.domain;

import java.util.Date;

public class TbCommentReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_reply.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_reply.reply_type
     *
     * @mbggenerated
     */
    private String replyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_reply.reply_id
     *
     * @mbggenerated
     */
    private Long replyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_reply.comment_id
     *
     * @mbggenerated
     */
    private Long commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_reply.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_reply.from_uid
     *
     * @mbggenerated
     */
    private Long fromUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_reply.from_thumb_img
     *
     * @mbggenerated
     */
    private String fromThumbImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_reply.from_nick_name
     *
     * @mbggenerated
     */
    private String fromNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_reply.to_uid
     *
     * @mbggenerated
     */
    private Long toUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_reply.to_thumb_img
     *
     * @mbggenerated
     */
    private String toThumbImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_reply.to_nick_name
     *
     * @mbggenerated
     */
    private String toNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment_reply.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_reply.id
     *
     * @return the value of tb_comment_reply.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_reply.id
     *
     * @param id the value for tb_comment_reply.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_reply.reply_type
     *
     * @return the value of tb_comment_reply.reply_type
     *
     * @mbggenerated
     */
    public String getReplyType() {
        return replyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_reply.reply_type
     *
     * @param replyType the value for tb_comment_reply.reply_type
     *
     * @mbggenerated
     */
    public void setReplyType(String replyType) {
        this.replyType = replyType == null ? null : replyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_reply.reply_id
     *
     * @return the value of tb_comment_reply.reply_id
     *
     * @mbggenerated
     */
    public Long getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_reply.reply_id
     *
     * @param replyId the value for tb_comment_reply.reply_id
     *
     * @mbggenerated
     */
    public void setReplyId(Long replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_reply.comment_id
     *
     * @return the value of tb_comment_reply.comment_id
     *
     * @mbggenerated
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_reply.comment_id
     *
     * @param commentId the value for tb_comment_reply.comment_id
     *
     * @mbggenerated
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_reply.content
     *
     * @return the value of tb_comment_reply.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_reply.content
     *
     * @param content the value for tb_comment_reply.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_reply.from_uid
     *
     * @return the value of tb_comment_reply.from_uid
     *
     * @mbggenerated
     */
    public Long getFromUid() {
        return fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_reply.from_uid
     *
     * @param fromUid the value for tb_comment_reply.from_uid
     *
     * @mbggenerated
     */
    public void setFromUid(Long fromUid) {
        this.fromUid = fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_reply.from_thumb_img
     *
     * @return the value of tb_comment_reply.from_thumb_img
     *
     * @mbggenerated
     */
    public String getFromThumbImg() {
        return fromThumbImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_reply.from_thumb_img
     *
     * @param fromThumbImg the value for tb_comment_reply.from_thumb_img
     *
     * @mbggenerated
     */
    public void setFromThumbImg(String fromThumbImg) {
        this.fromThumbImg = fromThumbImg == null ? null : fromThumbImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_reply.from_nick_name
     *
     * @return the value of tb_comment_reply.from_nick_name
     *
     * @mbggenerated
     */
    public String getFromNickName() {
        return fromNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_reply.from_nick_name
     *
     * @param fromNickName the value for tb_comment_reply.from_nick_name
     *
     * @mbggenerated
     */
    public void setFromNickName(String fromNickName) {
        this.fromNickName = fromNickName == null ? null : fromNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_reply.to_uid
     *
     * @return the value of tb_comment_reply.to_uid
     *
     * @mbggenerated
     */
    public Long getToUid() {
        return toUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_reply.to_uid
     *
     * @param toUid the value for tb_comment_reply.to_uid
     *
     * @mbggenerated
     */
    public void setToUid(Long toUid) {
        this.toUid = toUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_reply.to_thumb_img
     *
     * @return the value of tb_comment_reply.to_thumb_img
     *
     * @mbggenerated
     */
    public String getToThumbImg() {
        return toThumbImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_reply.to_thumb_img
     *
     * @param toThumbImg the value for tb_comment_reply.to_thumb_img
     *
     * @mbggenerated
     */
    public void setToThumbImg(String toThumbImg) {
        this.toThumbImg = toThumbImg == null ? null : toThumbImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_reply.to_nick_name
     *
     * @return the value of tb_comment_reply.to_nick_name
     *
     * @mbggenerated
     */
    public String getToNickName() {
        return toNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_reply.to_nick_name
     *
     * @param toNickName the value for tb_comment_reply.to_nick_name
     *
     * @mbggenerated
     */
    public void setToNickName(String toNickName) {
        this.toNickName = toNickName == null ? null : toNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment_reply.create_time
     *
     * @return the value of tb_comment_reply.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment_reply.create_time
     *
     * @param createTime the value for tb_comment_reply.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}