package cn.edu.xupt.help.framework.domain;

import java.util.Date;

public class TbGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.user_nick_name
     *
     * @mbggenerated
     */
    private String userNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.user_pic
     *
     * @mbggenerated
     */
    private String userPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.price
     *
     * @mbggenerated
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.thum_pic
     *
     * @mbggenerated
     */
    private String thumPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.main_pic
     *
     * @mbggenerated
     */
    private String mainPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.long_pic
     *
     * @mbggenerated
     */
    private String longPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.category_id
     *
     * @mbggenerated
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.prase_count
     *
     * @mbggenerated
     */
    private Long praseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.comment_count
     *
     * @mbggenerated
     */
    private Long commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.is_top
     *
     * @mbggenerated
     */
    private String isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.id
     *
     * @return the value of tb_goods.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.id
     *
     * @param id the value for tb_goods.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.user_id
     *
     * @return the value of tb_goods.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.user_id
     *
     * @param userId the value for tb_goods.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.username
     *
     * @return the value of tb_goods.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.username
     *
     * @param username the value for tb_goods.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.user_nick_name
     *
     * @return the value of tb_goods.user_nick_name
     *
     * @mbggenerated
     */
    public String getUserNickName() {
        return userNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.user_nick_name
     *
     * @param userNickName the value for tb_goods.user_nick_name
     *
     * @mbggenerated
     */
    public void setUserNickName(String userNickName) {
        this.userNickName = userNickName == null ? null : userNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.user_pic
     *
     * @return the value of tb_goods.user_pic
     *
     * @mbggenerated
     */
    public String getUserPic() {
        return userPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.user_pic
     *
     * @param userPic the value for tb_goods.user_pic
     *
     * @mbggenerated
     */
    public void setUserPic(String userPic) {
        this.userPic = userPic == null ? null : userPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_name
     *
     * @return the value of tb_goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_name
     *
     * @param goodsName the value for tb_goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.price
     *
     * @return the value of tb_goods.price
     *
     * @mbggenerated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.price
     *
     * @param price the value for tb_goods.price
     *
     * @mbggenerated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.content
     *
     * @return the value of tb_goods.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.content
     *
     * @param content the value for tb_goods.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.thum_pic
     *
     * @return the value of tb_goods.thum_pic
     *
     * @mbggenerated
     */
    public String getThumPic() {
        return thumPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.thum_pic
     *
     * @param thumPic the value for tb_goods.thum_pic
     *
     * @mbggenerated
     */
    public void setThumPic(String thumPic) {
        this.thumPic = thumPic == null ? null : thumPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.main_pic
     *
     * @return the value of tb_goods.main_pic
     *
     * @mbggenerated
     */
    public String getMainPic() {
        return mainPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.main_pic
     *
     * @param mainPic the value for tb_goods.main_pic
     *
     * @mbggenerated
     */
    public void setMainPic(String mainPic) {
        this.mainPic = mainPic == null ? null : mainPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.long_pic
     *
     * @return the value of tb_goods.long_pic
     *
     * @mbggenerated
     */
    public String getLongPic() {
        return longPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.long_pic
     *
     * @param longPic the value for tb_goods.long_pic
     *
     * @mbggenerated
     */
    public void setLongPic(String longPic) {
        this.longPic = longPic == null ? null : longPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.category_id
     *
     * @return the value of tb_goods.category_id
     *
     * @mbggenerated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.category_id
     *
     * @param categoryId the value for tb_goods.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.prase_count
     *
     * @return the value of tb_goods.prase_count
     *
     * @mbggenerated
     */
    public Long getPraseCount() {
        return praseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.prase_count
     *
     * @param praseCount the value for tb_goods.prase_count
     *
     * @mbggenerated
     */
    public void setPraseCount(Long praseCount) {
        this.praseCount = praseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.comment_count
     *
     * @return the value of tb_goods.comment_count
     *
     * @mbggenerated
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.comment_count
     *
     * @param commentCount the value for tb_goods.comment_count
     *
     * @mbggenerated
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.is_top
     *
     * @return the value of tb_goods.is_top
     *
     * @mbggenerated
     */
    public String getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.is_top
     *
     * @param isTop the value for tb_goods.is_top
     *
     * @mbggenerated
     */
    public void setIsTop(String isTop) {
        this.isTop = isTop == null ? null : isTop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.create_time
     *
     * @return the value of tb_goods.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.create_time
     *
     * @param createTime the value for tb_goods.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.status
     *
     * @return the value of tb_goods.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.status
     *
     * @param status the value for tb_goods.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}