package cn.edu.xupt.help.framework.domain;

public class TbMessageImages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message_images.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message_images.message_id
     *
     * @mbggenerated
     */
    private Long messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message_images.image_url
     *
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message_images.id
     *
     * @return the value of tb_message_images.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message_images.id
     *
     * @param id the value for tb_message_images.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message_images.message_id
     *
     * @return the value of tb_message_images.message_id
     *
     * @mbggenerated
     */
    public Long getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message_images.message_id
     *
     * @param messageId the value for tb_message_images.message_id
     *
     * @mbggenerated
     */
    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message_images.image_url
     *
     * @return the value of tb_message_images.image_url
     *
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message_images.image_url
     *
     * @param imageUrl the value for tb_message_images.image_url
     *
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }
}