package cn.edu.xupt.help.framework.domain;

public class TbMessageCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message_category.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message_category.category_name
     *
     * @mbggenerated
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_message_category.category_pic
     *
     * @mbggenerated
     */
    private String categoryPic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message_category.id
     *
     * @return the value of tb_message_category.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message_category.id
     *
     * @param id the value for tb_message_category.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message_category.category_name
     *
     * @return the value of tb_message_category.category_name
     *
     * @mbggenerated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message_category.category_name
     *
     * @param categoryName the value for tb_message_category.category_name
     *
     * @mbggenerated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_message_category.category_pic
     *
     * @return the value of tb_message_category.category_pic
     *
     * @mbggenerated
     */
    public String getCategoryPic() {
        return categoryPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_message_category.category_pic
     *
     * @param categoryPic the value for tb_message_category.category_pic
     *
     * @mbggenerated
     */
    public void setCategoryPic(String categoryPic) {
        this.categoryPic = categoryPic == null ? null : categoryPic.trim();
    }
}