package cn.edu.xupt.help.framework.domain;

public class TbSwiper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_swiper.swiper_id
     *
     * @mbggenerated
     */
    private Integer swiperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_swiper.swiper_image_url
     *
     * @mbggenerated
     */
    private String swiperImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_swiper.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_swiper.swiper_id
     *
     * @return the value of tb_swiper.swiper_id
     *
     * @mbggenerated
     */
    public Integer getSwiperId() {
        return swiperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_swiper.swiper_id
     *
     * @param swiperId the value for tb_swiper.swiper_id
     *
     * @mbggenerated
     */
    public void setSwiperId(Integer swiperId) {
        this.swiperId = swiperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_swiper.swiper_image_url
     *
     * @return the value of tb_swiper.swiper_image_url
     *
     * @mbggenerated
     */
    public String getSwiperImageUrl() {
        return swiperImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_swiper.swiper_image_url
     *
     * @param swiperImageUrl the value for tb_swiper.swiper_image_url
     *
     * @mbggenerated
     */
    public void setSwiperImageUrl(String swiperImageUrl) {
        this.swiperImageUrl = swiperImageUrl == null ? null : swiperImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_swiper.status
     *
     * @return the value of tb_swiper.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_swiper.status
     *
     * @param status the value for tb_swiper.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}