package cn.edu.xupt.help.dept.mapper;

import cn.edu.xupt.help.framework.domain.TbDept;
import cn.edu.xupt.help.framework.domain.TbDeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TbDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbggenerated
     */
    int countByExample(TbDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbggenerated
     */
    int deleteByExample(TbDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbggenerated
     */
    int insert(TbDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbggenerated
     */
    int insertSelective(TbDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbggenerated
     */
    List<TbDept> selectByExample(TbDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbggenerated
     */
    TbDept selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbDept record, @Param("example") TbDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbDept record, @Param("example") TbDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbDept record);
}