package cn.edu.xupt.help.swiper.mapper;

import cn.edu.xupt.help.framework.domain.TbSwiper;
import cn.edu.xupt.help.framework.domain.TbSwiperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TbSwiperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_swiper
     *
     * @mbggenerated
     */
    int countByExample(TbSwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_swiper
     *
     * @mbggenerated
     */
    int deleteByExample(TbSwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_swiper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long swiperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_swiper
     *
     * @mbggenerated
     */
    int insert(TbSwiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_swiper
     *
     * @mbggenerated
     */
    int insertSelective(TbSwiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_swiper
     *
     * @mbggenerated
     */
    List<TbSwiper> selectByExample(TbSwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_swiper
     *
     * @mbggenerated
     */
    TbSwiper selectByPrimaryKey(Long swiperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_swiper
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbSwiper record, @Param("example") TbSwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_swiper
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbSwiper record, @Param("example") TbSwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_swiper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbSwiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_swiper
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbSwiper record);
}