package cn.edu.xupt.help.goods.mapper;

import cn.edu.xupt.help.framework.domain.TbGoodsCategory;
import cn.edu.xupt.help.framework.domain.TbGoodsCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TbGoodsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_category
     *
     * @mbggenerated
     */
    int countByExample(TbGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_category
     *
     * @mbggenerated
     */
    int deleteByExample(TbGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_category
     *
     * @mbggenerated
     */
    int insert(TbGoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_category
     *
     * @mbggenerated
     */
    int insertSelective(TbGoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_category
     *
     * @mbggenerated
     */
    List<TbGoodsCategory> selectByExample(TbGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_category
     *
     * @mbggenerated
     */
    TbGoodsCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbGoodsCategory record, @Param("example") TbGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbGoodsCategory record, @Param("example") TbGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbGoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbGoodsCategory record);
}