package cn.edu.xupt.help.comment.mapper;

import cn.edu.xupt.help.framework.domain.TbCommentReply;
import cn.edu.xupt.help.framework.domain.TbCommentReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface TbCommentReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    int countByExample(TbCommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    int deleteByExample(TbCommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    int insert(TbCommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    int insertSelective(TbCommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    List<TbCommentReply> selectByExample(TbCommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    TbCommentReply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbCommentReply record, @Param("example") TbCommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbCommentReply record, @Param("example") TbCommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbCommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_comment_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbCommentReply record);
}